[2021-08-21 07:07:45,988: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-08-21 07:07:45,997: INFO/MainProcess] mingle: searching for neighbors
[2021-08-21 07:07:47,020: INFO/MainProcess] mingle: all alone
[2021-08-21 07:07:47,032: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-08-21 07:07:47,033: INFO/MainProcess] celery@f872da4b0717 ready.
[2021-08-21 07:07:47,035: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[582e706b-cfb3-4b5f-8e60-7e22ed641143]  
[2021-08-21 07:07:51,561: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-08-21 07:07:57,051: INFO/ForkPoolWorker-3] Task tasks.sample_tasks.create_task[582e706b-cfb3-4b5f-8e60-7e22ed641143] succeeded in 10.015307280999878s: True
[2021-08-21 07:08:00,562: INFO/MainProcess] Received task: tasks.sample_tasks.create_task[ab71b187-47e0-4af2-a159-e126804a9a24]  
[2021-08-21 07:08:10,572: INFO/ForkPoolWorker-3] Task tasks.sample_tasks.create_task[ab71b187-47e0-4af2-a159-e126804a9a24] succeeded in 10.008608098999503s: True
